import React from "react";
import { PlayCircle, Award, Clock, BarChart3, CheckCircle } from "lucide-react";

export const Courses = ({ selectedCourse, onStartQuiz }) => {
  const courseContent = {
    "renewable-energy": {
      title: "Renewable Energy Revolution",
      icon: "⚡",
      description: "Master the fundamentals of sustainable energy sources",
      modules: [
        {
          id: 1,
          title: "Introduction to Renewable Energy",
          duration: "15 min",
          completed: false,
          content:
            "Learn about different types of renewable energy sources and their importance for our planet.",
        },
        {
          id: 2,
          title: "Solar Power Technology",
          duration: "20 min",
          completed: false,
          content:
            "Discover how solar panels work and their environmental benefits.",
        },
        {
          id: 3,
          title: "Wind Energy Systems",
          duration: "18 min",
          completed: false,
          content: "Explore wind turbine technology and wind farm operations.",
        },
      ],
      quiz: {
        title: "Renewable Energy Quiz",
        questions: [
          {
            question:
              "Which renewable energy source is generated by the movement of air?",
            options: ["Solar", "Wind", "Hydro", "Geothermal"],
            correct: 1,
            explanation:
              "Wind energy harnesses the kinetic energy of moving air to generate electricity through wind turbines.",
          },
          {
            question:
              "What percentage of global electricity comes from renewable sources as of 2023?",
            options: ["15%", "25%", "30%", "45%"],
            correct: 2,
            explanation:
              "Renewable energy sources now account for approximately 30% of global electricity generation.",
          },
          {
            question:
              "Solar panels convert sunlight into electricity through which process?",
            options: [
              "Photosynthesis",
              "Photovoltaic effect",
              "Nuclear fusion",
              "Combustion",
            ],
            correct: 1,
            explanation:
              "The photovoltaic effect allows solar cells to convert photons from sunlight directly into electrical energy.",
          },
        ],
      },
    },
    "ocean-conservation": {
      title: "Ocean Conservation",
      icon: "🌊",
      description: "Protect marine ecosystems and ocean biodiversity",
      modules: [
        {
          id: 1,
          title: "Ocean Ecosystems",
          duration: "20 min",
          completed: false,
          content: "Understanding marine food chains and biodiversity.",
        },
        {
          id: 2,
          title: "Plastic Pollution Crisis",
          duration: "25 min",
          completed: false,
          content: "The impact of plastic waste on marine life and ecosystems.",
        },
        {
          id: 3,
          title: "Conservation Strategies",
          duration: "15 min",
          completed: false,
          content: "Effective methods for protecting our oceans.",
        },
      ],
      quiz: {
        title: "Ocean Conservation Quiz",
        questions: [
          {
            question: "How much plastic waste enters our oceans annually?",
            options: [
              "1 million tons",
              "8 million tons",
              "15 million tons",
              "25 million tons",
            ],
            correct: 1,
            explanation:
              "Approximately 8 million tons of plastic waste enters our oceans every year.",
          },
          {
            question:
              "What percentage of Earth's oxygen is produced by ocean phytoplankton?",
            options: ["25%", "50%", "70%", "90%"],
            correct: 2,
            explanation:
              "Ocean phytoplankton produces about 70% of the oxygen we breathe.",
          },
        ],
      },
    },
    "sustainable-living": {
      title: "Sustainable Living",
      icon: "🌱",
      description: "Adopt eco-friendly practices in your daily life",
      modules: [
        {
          id: 1,
          title: "Reduce, Reuse, Recycle",
          duration: "12 min",
          completed: false,
          content: "Master the 3 Rs of sustainable living.",
        },
        {
          id: 2,
          title: "Energy Conservation",
          duration: "18 min",
          completed: false,
          content: "Simple ways to reduce your carbon footprint at home.",
        },
      ],
      quiz: {
        title: "Sustainable Living Quiz",
        questions: [
          {
            question: "Which activity has the largest carbon footprint?",
            options: ["Driving", "Flying", "Meat consumption", "Home heating"],
            correct: 1,
            explanation:
              "Air travel typically has the highest carbon footprint per mile traveled.",
          },
        ],
      },
    },
  };

  const course =
    courseContent[selectedCourse?.id] || courseContent["renewable-energy"];

  return (
    <div className="max-w-4xl mx-auto p-6">
      {/* Course Header */}
      <div className="bg-white rounded-2xl p-8 shadow-lg mb-8">
        <div className="flex items-start justify-between">
          <div className="flex items-center space-x-4">
            <div className="text-6xl">{course.icon}</div>
            <div>
              <h1 className="text-3xl font-bold text-gray-800 mb-2">
                {course.title}
              </h1>
              <p className="text-gray-600 text-lg mb-4">{course.description}</p>
              <div className="flex items-center space-x-6 text-sm text-gray-500">
                <div className="flex items-center space-x-1">
                  <Clock className="h-4 w-4" />
                  <span>
                    {course.modules.reduce(
                      (acc, module) => acc + parseInt(module.duration),
                      0
                    )}{" "}
                    min total
                  </span>
                </div>
                <div className="flex items-center space-x-1">
                  <BarChart3 className="h-4 w-4" />
                  <span>{selectedCourse?.difficulty || "Intermediate"}</span>
                </div>
                <div className="flex items-center space-x-1">
                  <Award className="h-4 w-4" />
                  <span>{selectedCourse?.xpReward || 150} XP</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Course Modules */}
      <div className="space-y-6">
        <h2 className="text-2xl font-bold text-gray-800 mb-6">
          Course Modules
        </h2>
        {course.modules.map((module, index) => (
          <div
            key={module.id}
            className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl transition-shadow duration-300"
          >
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center space-x-3 mb-3">
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${
                      module.completed
                        ? "bg-green-100 text-green-700"
                        : "bg-gray-100 text-gray-600"
                    }`}
                  >
                    {module.completed ? (
                      <CheckCircle className="h-5 w-5" />
                    ) : (
                      index + 1
                    )}
                  </div>
                  <h3 className="text-lg font-semibold text-gray-800">
                    {module.title}
                  </h3>
                  <span className="text-sm text-gray-500 bg-gray-100 px-2 py-1 rounded-full">
                    {module.duration}
                  </span>
                </div>
                <p className="text-gray-600 mb-4">{module.content}</p>
              </div>
              <button className="flex items-center space-x-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors duration-200">
                <PlayCircle className="h-5 w-5" />
                <span>{module.completed ? "Review" : "Start"}</span>
              </button>
            </div>
          </div>
        ))}

        {/* Final Quiz */}
        <div className="bg-gradient-to-r from-blue-600 to-green-600 rounded-xl p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-xl font-bold mb-2">{course.quiz.title}</h3>
              <p className="opacity-90 mb-4">
                Test your knowledge and earn XP!
              </p>
              <div className="flex items-center space-x-4 text-sm">
                <span>{course.quiz.questions.length} Questions</span>
                <span>•</span>
                <span>{selectedCourse?.xpReward || 150} XP Reward</span>
              </div>
            </div>
            <button
              onClick={() => onStartQuiz(course.quiz)}
              className="bg-white/20 hover:bg-white/30 backdrop-blur-sm text-white px-6 py-3 rounded-lg font-semibold transition-all duration-200"
            >
              Start Quiz
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
